# .github/workflows/build-and-deploy.yml
name: build-and-deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install
        run: npm ci

      # 🔓 Hotfix: NO romper por ESLint en CI (CRA)
      # CI=false: evita "warnings como errores"
      # DISABLE_ESLINT_PLUGIN=true: CRA no ejecuta ESLint durante el build
      - name: Build
        run: npm run build
        env:
          CI: "false"
          DISABLE_ESLINT_PLUGIN: "true"

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build
          force_orphan: true